version: "3.4"
services:
  www:
    build:
      context: .
    volumes:
      - ./:/code
    environment:
      # These are for Django
      - POSTGRES_HOSTNAME=db
      - POSTGRES_DATABASE=datacube
      - POSTGRES_USER=datacube
      - POSTGRES_PASSWORD=opendatacubepassword
      # These are for ODC
      - DB_HOSTNAME=db
      - DB_USERNAME=datacube
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=odc
    ports: 
      - 80:8000
    depends_on:
      - 'db'

  myrabbit:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"
  celeryworker:
    build:
      context: .
    volumes:
      - ./:/code
    environment:
      # These are for ODC
      - DB_HOSTNAME=db
      - DB_USERNAME=datacube
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=odc
    command: ['celery', '-A', 'data_cube_ui.celery', 'worker', '--loglevel', 'info']
    links:
        - myrabbit

  redis:
    image: redis

  db:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_USER=datacube
      - POSTGRES_PASSWORD=opendatacubepassword
    ports:
      - '5432:5432'
